data:
  - id: 3
    value: č.10
    name: Brunclíková
    trieda: 1.D
    april:
    color: violet
    place: trieda
  - id: 4
    value: č.9
    name: Komjatová
    trieda: 4.B,C
    april:
    color: amber
    place: trieda
  - id: 5
    value: č.7
    name: Lehutová
    trieda: 2.B
    april: Pálenka
    color: purple
    place: trieda
  - id: 6
    value: č.12
    name: Lenčéšová
    trieda: 2.C
    april:
    color: stone
    place: trieda 
  - id: 7
    value: č.5
    name: Supeková
    trieda: 1.A
    april:
    color: yellow
    place: trieda
  - id: 8
    value: č.6
    name: Turoci
    trieda: 1.C
    april:
    color: green
    place: trieda
  - id: 9
    value: č.8
    name: Tureková
    trieda: 3.C
    april:
    color: pink
    place: trieda
  - id: 10
    value: č.4
    name: Lomen
    trieda: 2.A
    april:
    color: orange
    place: trieda
  - id: 11
    value: č.3
    name: Smíkalová
    trieda: 3.B
    april: Šmikalova
    color: gray
    place: trieda
  - id: 12
    value: č.11
    name: Slováková
    trieda: 1.B
    april:
    color: red
    place: trieda
  - id: 13
    value: č.13
    name: Srnec
    trieda: 4.A,C
    april:
    color: sky
    place: trieda
  - id: 14
    value: č.16
    name: Urbanová
    trieda: 3.A
    april:
    color: fuchsia
    place: trieda
pin:
  - id: 1
    pin: 6162636465
    admin: true
  - id: 2
    pin: 616263
    admin: true
  - id: 3
    pin: 515253
    admin: false
  - id: 4
    pin: 515254
    admin: false
  - id: 5
    pin: 141082
    admin: false
  - id: 6
    pin: 515256
    admin: false 
  - id: 7
    pin: 515257
    admin: false
  - id: 8
    pin: 515258
    admin: false
  - id: 9
    pin: 515159
    admin: false
  - id: 11
    pin: 7777
    admin: false
  - id: 13
    pin: 152837
    admin: false
places:
  - category: Trieda
    id: trieda
  - category: Školsky dvor
    id: skolsky_dvor
  # - category: Školsky dvor z boku
  #   id: skolsky_dvor_bok
  - category: Záhradka
    id: zahradka
  - category: Ihrisko pri záhradke
    id: ihrisko
  - category: Telocvična
    id: telocvicna
  - category: Herňa
    id: herna
  - category: Školská jedáleň
    id: jedalen
