data:
  - id: 3
    value: č.3
    name: Smikalova 3.B
    april: Šmikalova
    color: yellow
    place: trieda
  - id: 4
    value: č.4
    name: Lomen 2.A
    april:
    color: purple
    place: trieda
  - id: 5
    value: č.7
    name: Lehutova 2.B
    april: Pálenka
    color: pink
    place: trieda
  - id: 6
    value: č.12
    name: Lenčešová 2.C
    april:
    color: orange
    place: trieda 
  - id: 7
    value: č.5
    name: Supeková 1.A
    april:
    color: blue
    place: trieda
  - id: 8
    value: č.6
    name: Turoci 1.C
    april:
    color: blue
    place: trieda
  - id: 9
    value: č.8
    name: Tureková 3.C
    april:
    color: blue
    place: trieda
  - id: 10
    value: č.9
    name: Komjatová 4.B,C
    april:
    color: blue
    place: trieda
  - id: 11
    value: č.10
    name: Brunclíková 1.D
    april:
    color: blue
    place: trieda
  - id: 12
    value: č.11
    name: Slováková 1.B
    april:
    color: blue
    place: trieda
  - id: 13
    value: č.13
    name: Srnec 4.A,C
    april:
    color: blue
    place: trieda
  - id: 14
    value: č.16
    name: Urbanová 3.A
    april:
    color: blue
    place: trieda
pin:
  - id: 1
    pin: 6162636465
    admin: true
  - id: 2
    pin: 616263
    admin: true
  - id: 3
    pin: 515253
    admin: false
places:
  - category: Trieda
    id: trieda
  - category: Školsky dvor zozadu
    id: skolsky_dvor
  - category: Školsky dvor z boku
    id: skolsky_dvor_bok
  - category: Zahradka
    id: zahradka
